Helpers/Models/Checkbox.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Helpers.Models
{
    public class Checkbox
    {
        public int IdHobby { get; set; }
        public string NombreHobby { get; set; }
        public bool seleccionado { get; set; }
    }
}

Helpers/Models/Datos.cs
using Microsoft.CSharp.RuntimeBinder;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Reflection;
using System.Web;

namespace Helpers.Models
{
    public class Datos
    {
        [Required(ErrorMessage ="Digita una cédula")]
        public string cedula { get; set; }
        [Required(ErrorMessage = "Digita un nombre")]
        public string nombre { get; set; }

        [Required(ErrorMessage = "Digita un apellido")]
        public string apellido { get; set; }
        [Required]
        [Range(16,100,ErrorMessage ="Digita una edad mayor de 15")]
        public int edad { get; set; }
        [Required(ErrorMessage ="agrega un telefono")]
        public string telefono { get; set; }

        [Required(ErrorMessage ="Ingresa un correo Válido")]
        [EmailAddress(ErrorMessage ="Ingresa un correo Válido")]
        public string correo { get; set; }
        [Required]
        public Sexo Sexo { get; set; }
        [Required]
        public string EstadoCivil { get; set; }
       
        public List<Checkbox> Hobbys { get; set; }
       

    }
 
    public enum Sexo
    {
        
        Masculino,
        Femenino,
    }
}

Helpers/Controllers/DatosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using Helpers.Models;

namespace Helpers.Controllers
{
    public class DatosController : Controller
    {
        // GET: Datos
        public ActionResult Formulario()
        {
            Datos lista = new Datos();

            List<Checkbox> listado = new List<Checkbox>();
            listado.Add(new Checkbox() { IdHobby = 1, NombreHobby = "Nadar", seleccionado = false });
            listado.Add(new Checkbox() { IdHobby = 2, NombreHobby = "Leer", seleccionado = false });
            listado.Add(new Checkbox() { IdHobby = 3, NombreHobby = "Escuchar Musica", seleccionado = false });
            listado.Add(new Checkbox() { IdHobby = 4, NombreHobby = "Correr en el parque", seleccionado = false });
            lista.Hobbys = listado;
            
            return View(lista);
        }
        [HttpPost]
        public ActionResult Formulario(Datos usuario)
        {
            


            if (ModelState.IsValid) {
                StringBuilder sb = new StringBuilder();
                foreach (var item in usuario.Hobbys)
                {
                    if (item.seleccionado)
                    {
                        sb.Append(item.NombreHobby + ",");
                    }
                }
                TempData["hobbys"] =sb;
                return RedirectToAction("Usuario", usuario);

            }
            else
            {
                return View(usuario);
            }
        }
        public ActionResult Usuario(Datos user)
        {
            if (TempData["hobbys"]!=null)
            {
                ViewBag.mensaje = TempData["hobbys"].ToString();
            }

           
            return View(user);
        }
       
    }
}

Helpers/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Helpers.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }


    }
}

Helpers/Views/Datos/Formulario.cshtml
@model Helpers.Models.Datos
@using Helpers.Models

@{
    /**/

    ViewBag.Title = "Formulario";
}


<div class="container">
    <div class="row">
        <div class="con">
            @Html.LabelForModel("Formulario", new { @class = "txt txt-uppercase" })
            @using (Html.BeginForm("Formulario", "Datos", FormMethod.Post))
            {
                <div class="form-row">
                    <div class="form-group col-md-6">

                        @Html.LabelFor(model => model.nombre, new { @class = "label" })


                        @Html.EditorFor(model => model.nombre, new { htmlAttributes = new { @class = "form-control inp" } })
                        @Html.ValidationMessageFor(model => model.nombre, "", new { @class = "text-danger" })



                    </div>
                    <div class="form-group col-md-6">
                        @Html.LabelFor(model => model.apellido, new { @class = "label" })
                        @Html.EditorFor(model => model.apellido, new { htmlAttributes = new { @class = "form-control inp" } })
                        @Html.ValidationMessageFor(model => model.apellido, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-6">
                        @Html.LabelFor(model => model.telefono, new { @class = "label" })
                        @Html.EditorFor(model => model.telefono, new { htmlAttributes = new { @class = "form-control inp" } })
                        @Html.ValidationMessageFor(model => model.telefono, "", new { @class = "text-danger" })
                    </div>
                    <div class="form-group col-md-6">
                        @Html.LabelFor(model => model.correo, new { @class = "label" })
                        @Html.EditorFor(model => model.correo, new { htmlAttributes = new { @class = "form-control inp" } })
                        @Html.ValidationMessageFor(model => model.correo, "", new { @class = "text-danger" })
                    </div>
                    <div class="form-group col-md-6">
                        @Html.LabelFor(model => model.edad, new { @class = "label" })
                        @Html.EditorFor(model => model.edad, new { htmlAttributes = new { @class = "form-control inp" } })
                        @Html.ValidationMessageFor(model => model.edad, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-6">
                        @Html.LabelFor(model => model.cedula, new { @class = "label" })
                        @Html.EditorFor(model => model.cedula, new { htmlAttributes = new { @class = "form-control inp" } })
                        @Html.ValidationMessageFor(model => model.cedula, "", new { @class = "text-danger" })
                    </div>
                    <div class="form-group col-md-6">
                        @Html.LabelForModel("Género", new { @class = "label" })
                        @Html.DropDownListFor(m => m.Sexo,
                                          new SelectList(Enum.GetValues(typeof(Sexo))),new { @class="form-control m"})
                    </div>
                </div>
                <div> @Html.Label("Estado Civil", new { @class = "estado" })</div>
                <div class="col-md-3 ">

                    <div class="form-group">

                        @Html.RadioButtonFor(model => model.EstadoCivil, "Casado", new { htmlAttributes = new { @class = "form-control inp" } })
                        @Html.LabelFor(model => model.EstadoCivil, "Casado", new { @class = "label" })

                    </div>
                    <div class="form-group">
                        @Html.RadioButtonFor(model => model.EstadoCivil, "Soltero", new { @id = "soltero" })
                        @Html.Label("soltero", "Soltero", new { @class = "label" })
                    </div>

                </div>
                <div class="form-group">

                    @Html.RadioButtonFor(model => model.EstadoCivil, "Viudo", new { @id = "viudo" })
                    @Html.Label("viudo", "Viudo", new { @class = "label" })
                </div>
                <div class="form-group">
                    @Html.RadioButtonFor(model => model.EstadoCivil, "Unión Libre", new { @id = "union" })
                    @Html.Label("union", "Unión Libre", new { @class = "label" })
                </div>
                @Html.ValidationMessageFor(model => model.EstadoCivil, "", new { @class = "text-danger" })

                <div>@Html.LabelFor(model => model.Hobbys, new { @class = "ho" })</div>
                for (int i = 0; i < Model.Hobbys.Count; i++)
                {
                    <div class="col-md-7 hobbys">

                        @Html.CheckBoxFor(model => model.Hobbys[i].seleccionado)
                        @Html.DisplayFor(model => model.Hobbys[i].NombreHobby)
                        @Html.HiddenFor(model => model.Hobbys[i].IdHobby)
                        @Html.HiddenFor(model => model.Hobbys[i].NombreHobby)
                    </div>
                }

                <div class="bt">

                    <button type="submit" class="btn btn-success boton">Registrar</button>

                </div>

            }
        </div>
            </div>
</div>

Helpers/Views/Datos/Usuario.cshtml
@model Helpers.Models.Datos


@{
    ViewBag.Title = "Usuario";
}



<div class="container-fluid">
    <div class="row">
        @Html.Label("Usuario", new { @class = "lab" })
        <table class="table table-striped t">
            <tr>
                <th>@Html.DisplayNameFor(model => model.nombre)</th>
                <th>@Html.DisplayNameFor(model => model.apellido)</th>
                <th>@Html.DisplayNameFor(model => model.telefono)</th>
                <th>@Html.DisplayNameFor(model => model.correo)</th>
                <th>@Html.DisplayNameFor(model => model.cedula)</th>
                <th>@Html.DisplayNameFor(model => model.edad)</th>
                <th>@Html.DisplayNameFor(model => model.Sexo)</th>
                <th>@Html.DisplayNameFor(model => model.EstadoCivil)</th>
                <th>@Html.DisplayNameFor(model => model.Hobbys)</th>

            </tr>

            <tr>
                <td>@Html.DisplayFor(model => model.nombre)</td>
                <td>@Html.DisplayFor(model => model.apellido)</td>
                <td>@Html.DisplayFor(model => model.telefono)</td>
                <td>@Html.DisplayFor(model => model.correo)</td>
                <td>@Html.DisplayFor(model => model.cedula)</td>
                <td>@Html.DisplayFor(model => model.edad)</td>
                <td>@Html.DisplayFor(model => model.Sexo)</td>
                <td>@Html.DisplayFor(model => model.EstadoCivil)</td>
                <td>@ViewBag.mensaje</td>

            </tr>

        </table>
    </div>
</div>
<a href="@Url.Action("Index","Home")" class="btn btn-primary">Volver al Inicio</a>
     

Helpers/Views/Home/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <link href="~/Content/Style.css" rel="stylesheet" />

   
</head>
<body>
    <div>
        <div class="contenedor">
            <h1>Bienvenidos</h1>
            <p>Bienvenido a aplicación con asp .net Helpers Html por Albert de Jesús Mata Hernández 2017-4531 presiona el boton para pasar al formulario</p>
            <center><input type="button" value="Formulario" onclick="location.href='@Url.Action("Formulario", "Datos")'" class="btn btn-secondary btn-md" /></center>


        </div>
    </div>
   
</body>
</html>

Helpers/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    <link href="~/Content/Style.css" rel="stylesheet" />
    <link href="~/css/all.css" rel="stylesheet" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    
    <div class="container body-content">
        @RenderBody()
        <hr class="hr"/>
        <footer class="footer">
            <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>